name: "Run Reuse Action"
description: Runs the reuse-tool with various command line options
inputs:
  args:
    description: "The arguments to pass to the reuse-tool"
    required: true
  branch:
    description: "The branch of the tool to checkout"
    required: false
    default: "main"
runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      path: reuse-tool
      repository: UoMResearchIT/reuse-tool
      ref: ${{ inputs.branch }}

  - name: Setup Environment
    uses: getsentry/action-setup-venv@v2.1.0
    with:
      python-version: 3.12
      cache-dependency-path: |
        pyproject.toml
      venv-dir: reuse-tool-venv
      install-cmd: |
        pip install poetry~=1.3.0
        cd reuse-tool
        poetry install --no-interaction --only main
        poetry build --no-interaction
        pip install dist/*.whl

  - name: Run reuse
    shell: bash
    run: |
      source reuse-tool-venv/bin/activate
      reuse ${{ inputs.args }}
