name: "Run Reuse Action"
description: Runs the reuse-tool with various command line options
inputs:
  args:
    description: "The arguments to pass to the reuse-tool"
    required: true
  branch:
    description: "The branch of the tool to checkout"
    required: false
    default: "main"
runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      ref: ${{ inputs.branch }}

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'

  - name: Install dependencies
    run: |
      pip install poetry~=1.3.0
      poetry install --no-interaction --only main
      poetry build --no-interaction
      pip install dist/*.whl

  - name: Run reuse
    run: |
      reuse ${{ inputs.args }}
